### ISSUE TITLE
Error when minify rest in object destructuring expression

### ISSUE THREAD

**Issue by dima-lemeshko** [trullock/NUglify#246]
When try to minify js (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#rest_in_object_destructuring):

 Uglify.Js("({a, b, ...rest}) => { a; b;}");

Got error:
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.<Visit>b__54_0(ObjectLiteralProperty property)
   at NUglify.JavaScript.Syntax.AstNodeList.ForEach[TItem](Action`1 action)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(ObjectLiteral node)
   at NUglify.JavaScript.Syntax.ObjectLiteral.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.TreeVisitor.Visit(ParameterDeclaration node)
   at NUglify.JavaScript.Syntax.ParameterDeclaration.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.TreeVisitor.Visit(AstNodeList node)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(FunctionObject node)
   at NUglify.JavaScript.Syntax.FunctionObject.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BlockStatement node)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext, CodeSettings settings)
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)
   at ConsoleApp1.Program.Main(String[] args)

**Comment by trullock** [comment]
Is this on the latest version?

**Comment by dima-lemeshko** [comment]
Error reproduced in 1.13.8 (latest) and in 1.9.9 versions.

**Comment by trullock** [comment]
Fixed in 1.13.9
