### ISSUE TITLE
Lambda syntax error throws exception

### ISSUE THREAD

**Issue by andretmn** [trullock/NUglify#284]
I receive an exception when I run Uglify.Js which is unable to try-catch.
How can I try-catch it please?
Thanks
v1.16.4

   ```
at NUglify.JavaScript.JSParser.ParseArrowFunction(AstNode parameters)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseFunctionBody(BlockStatement body)
   at NUglify.JavaScript.JSParser.ParseFunctionPart2(FunctionType functionType, SourceContext context, BindingIdentifier name, ArrayLiteral computedName, Boolean isGenerator, Boolean isAsync)
   at NUglify.JavaScript.JSParser.ParseFunction(FunctionType functionType, SourceContext fncCtx)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseVarDecl(JSToken inToken)
   at NUglify.JavaScript.JSParser.ParseVariableStatement()
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)
   at Minifier.Minifiers.UglifyMinifier.MinifyJs(String path, String source) in C:\Dev\Minifier\Minifier\Minifiers\UglifyMinifier.cs:line 65
```

**Comment by trullock** [comment]
It's failing to parse a lambda, can you provide your JavaScript

**Comment by andretmn** [comment]
If you could provide an error for a case when parsing is imposible it could be very helpfull imo

**Comment by trullock** [comment]
It should do what you describe. There is a bug. 

Please provide the repro code

**Comment by andretmn** [comment]
Here is the original code which passes minification successfully:
```
var SurfSight = function (_settings) {
    this.showPlaceholder = (container) => {
        $(container).find('video').hide();
        $(container).find('.videoID').show();
    };
};
```

Here is the code which causes current crash. 
```
var SurfSight = function (_settings) {
    this.showPlaceholder (container) => {
        $(container).find('video').hide();
        $(container).find('.videoID').show();
    };
};
```

Here I change the row by removing the sign '=' to cause syntax error in purpose to check my minifier code stability:
`    this.showPlaceholder (container) => {`

**Comment by trullock** [comment]
Thanks, I'll take a look

**Comment by andretmn** [comment]
Thank you

**Comment by trullock** [comment]
Fixed in v1.16.6

**Comment by andretmn** [comment]
Hi. Thanks for the fix.
There is a proble to install this version yet.

Install-Package NUglify -Version 1.16.6
**>>NU1102: Unable to find package NUglify with version (>= 1.16.6)**

**Comment by trullock** [comment]
Ughh the build failed for some reason. Will look later

**Comment by trullock** [comment]
1.17.0 shoyuld publish shortly

**Comment by andretmn** [comment]
Thank you very much

**Comment by trullock** [comment]
Now fix your syntax error 😂

**Comment by andretmn** [comment]
😂 Thank you very much, friend
