### ISSUE TITLE
Value cannot be null. (Parameter 'meth')

### ISSUE THREAD

**Issue by shihmin88** [trullock/NUglify#356]
Are you using the latest verion of NUglify, especially if used through BunderMinifier? Update before raising a bug as your issue is probably already fixed.

**Describe the bug**
This problem occurs in certain windows environments
Do I lost some files? 

**To Reproduce**
Provide a minimal source code example AND how you are invoking NUglify

**Minified output or stack trace**

發生錯誤
Value cannot be null. (Parameter 'meth')
at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, MethodInfo meth)
at System.Text.RegularExpressions.RegexCompiler.Callvirt(MethodInfo mt)
at System.Text.RegularExpressions.RegexCompiler.GenerateOneCode()
at System.Text.RegularExpressions.RegexCompiler.GenerateForwardSection()
at System.Text.RegularExpressions.RegexCompiler.GenerateGo()
at System.Text.RegularExpressions.RegexLWCGCompiler.FactoryInstanceFromCode(RegexCode code, RegexOptions options)
at System.Text.RegularExpressions.Regex.Compile(RegexCode code, RegexOptions roptions)
at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
at NUglify.Css.CssParser..cctor()

**Excepted output code**
Provide the expected minified code

**Comment by trullock** [comment]
I need to input code that caused this, how do you expect me to help you?
