### ISSUE TITLE
throw System.NullReferenceException on the function Uglify.Js

### ISSUE THREAD

**Issue by Fioenix** [trullock/NUglify#36]
I minify a js file as below:
[source.txt](https://github.com/xoofx/NUglify/files/1520571/source.txt)

and get a NullReferenceException
Uglify.Js(source)' threw an exception of type 'System.NullReferenceException'

`  at NUglify.JavaScript.Syntax.MemberExpression.GetFunctionGuess(AstNode target)
   at NUglify.JavaScript.Syntax.BinaryExpression.GetFunctionGuess(AstNode target)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.GuessAtName(AstNode node)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(FunctionObject node)
   at NUglify.JavaScript.Syntax.FunctionObject.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BinaryExpression node)
   at NUglify.JavaScript.Syntax.BinaryExpression.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BlockStatement node)
   at NUglify.JavaScript.Syntax.BlockStatement.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.TreeVisitor.Visit(IfStatement node)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(IfStatement node)
   at NUglify.JavaScript.Syntax.IfStatement.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BlockStatement node)
   at NUglify.JavaScript.Syntax.BlockStatement.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(FunctionObject node)
   at NUglify.JavaScript.Syntax.FunctionObject.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.TreeVisitor.Visit(CallExpression node)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(CallExpression node)
   at NUglify.JavaScript.Syntax.CallExpression.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.TreeVisitor.Visit(UnaryExpression node)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(UnaryExpression node)
   at NUglify.JavaScript.Syntax.UnaryExpression.Accept(IVisitor visitor)
   at NUglify.JavaScript.Visitors.AnalyzeNodeVisitor.Visit(BlockStatement node)
   at NUglify.JavaScript.Syntax.BlockStatement.Accept(IVisitor visitor)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)`

**Comment by trullock** [comment]
I suspect this was fixed by #94 and 1.6.3, need to test this
