### ISSUE TITLE
Nested template literals having a space will make NUglify throw an exception.

### ISSUE THREAD

**Issue by SmGUzI** [trullock/NUglify#404]
Hello

I have created a system that takes compiled TypeScript code and minifies it among other things. While testing I have encountered an exception thrown by NUglify (a null reference exception) which was weird because the code was valid. 

After some testing I have found out template literals written as ` template `` `  with a space would sometimes cause an error, mostly when having nested template literals.  Writing them without a space doesn't seem to trigger the problem.   This is the most minimal case I could find:

```javascript
html `
    ${this.loading ? html `<div></div>` : null}
`;
```

Here is the stack trace:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at NUglify.JavaScript.JSParser.ParseExpression(AstNode leftHandSide, Boolean single, Boolean bCanAssign, JSToken inToken)
   at NUglify.JavaScript.JSParser.ParseExpression(Boolean single, JSToken inToken)
   at NUglify.JavaScript.JSParser.ParseTemplateLiteral()
   at NUglify.JavaScript.JSParser.ParseMemberExpression(AstNode expression, List`1 newContexts)
   at NUglify.JavaScript.JSParser.ParseLeftHandSideExpression(Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseUnaryExpression(Boolean& isLeftHandSideExpr, Boolean isMinus)
   at NUglify.JavaScript.JSParser.ParseExpressionStatement(Boolean fSourceElement)
   at NUglify.JavaScript.JSParser.ParseStatement(Boolean fSourceElement, Boolean skipImportantComment)
   at NUglify.JavaScript.JSParser.ParseStatements(BlockStatement block)
   at NUglify.JavaScript.JSParser.InternalParse()
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext)
   at NUglify.JavaScript.JSParser.Parse(DocumentContext sourceContext, CodeSettings settings)
   at NUglify.Uglify.Js(String source, String fileName, CodeSettings codeSettings)
```

**Comment by trullock** [comment]
How are you invoking NUglify with this? Can you show a complete example

**Comment by SmGUzI** [comment]
Sorry, here is how I invoke it in my test script:
```csharp
    static string Test() {
        string code = @"
            html `
                ${this.loading ? html `<div></div>` : null}
            `;
        ";
        return Uglify.Js(code).Code;
    }
```
Also, I forgot to mention, typescript compiles template literals with a space regardless of how you write it in the source files so it won't be compatible by default when using this kind of literals. I did some regex replacing to fix the issue for now and it seems to work.

**Comment by trullock** [comment]
well your input will evaluate to:

```
            html `
                <div></div>
            `
```

which isnt valid javascript.

Reopen if you have valid JS that has an issue

**Comment by SmGUzI** [comment]
It is valid JavaScript code  if the `html` template literal is defined, I don't know how it's not. I won't bother opening another issue but thank you for your time.
